apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-{{ $.Values.name }}"
  labels:
    {{- if $.Values.labels}}
    {{- toYaml $.Values.labels | nindent 4 }}
    {{- end}}
    app.kubernetes.io/name: {{ $.Values.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  ports:
    - port: {{ $.Values.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $.Values.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}