name: 'Test Go Action'
on:
  release:
    types: [published]
jobs:
  deploy-dev:
    name: 'Deploy to dev'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: https://github.com/actions/checkout@v4
      - name: Building
        uses: https://git.binom.pw/subochev/devops/build-gradle@main
        with:
          image_name: "device/ws"
          tag: ${{ gitea.ref_name }}
      - name: Publishing Gradle
        uses: https://git.binom.pw/subochev/devops/publish@main
        with:
          version: ${{ gitea.ref_name }}