replicaCount: 1
autoscaling:
  enabled: false
labels: [ ]
metrics: true
managementPort: 9090
port: 8080
imagePullSecrets: null
image:
  name: null
  pullPolicy: IfNotPresent
name: device-ws
ingress:
  host: '{{$.Values.name}}.{{$.Release.Namespace}}.com'
nats:
  server:
    host: null
deviceSecret: null
topicPrefix: "device"
pingInterval: "PT30S"
pingTimeout: "PT10S"
storage:
  accessKey: null
  secretKey: null
  url: null
  bucketName: null
  regin: null